stages:
  - deploy

deploy-job-master:
  stage: deploy
  image: docker:latest
  script:
    - docker ps
    - docker system prune -a --volumes -f
    - docker login -u alsunj -p $dockerhub
    - docker buildx build --progress=plain --force-rm --push -t alsunj/webapp:latest .
  only:
    - main 