services:
  sql:
    image: postgres:16
    container_name: trafficreport-sql
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3

volumes:
  sql-volume:
